wandb_version: 1

lr:
  desc: null
  value: 0.0005
step_size:
  desc: null
  value: 2000
gamma:
  desc: null
  value: 0.8
hid_lay_num:
  desc: null
  value: 5
kernel_size:
  desc: null
  value: 3
neu_num:
  desc: null
  value: 256
dic_neu_num:
  desc: null
  value: 64
dic_lay_num:
  desc: null
  value: 0
in_dim:
  desc: null
  value: 10
epoch:
  desc: null
  value: 4000
echo_step:
  desc: null
  value: 50
cs_pena:
  desc: null
  value: 1.0
time_fac:
  desc: null
  value: 1.0
rand_seed:
  desc: null
  value: 3024
speedup_rate:
  desc: null
  value:
  - 1.0
batch_size:
  desc: null
  value: 6
drop:
  desc: null
  value: 0.5
tot_t:
  desc: null
  value: 16
_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.17.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721391690
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 4
      - 13
      - 16
      - 23
      - 42
      4: 3.11.6
      5: 0.17.2
      8:
      - 5
      - 9
      13: linux-x86_64
